name: build
on: [push, pull_request]
jobs:
    applications:
        name: application test suite
        runs-on: ubuntu-latest
        timeout-minutes: 40
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: '7.x'
            - name: Package application
              run: |
                  echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
                  chmod +x mvnw
                  ./mvnw -ntp package -DskipTests -e -U
